#!/bin/bash

# Build a minideb image for each supported dist

set -e
set -u
set -o pipefail

DISTS="jessie
stretch
buster
buster-snapshot
unstable
"

for DIST in $DISTS; do
    ./buildone "$DIST"
done
