#!/bin/bash

set -e
set -u

DISTS="jessie
unstable
wheezy
"
LATEST=jessie

BASENAME=bitnami/minideb
GCR_BASENAME=gcr.io/bitnami-containers/minideb

mkdir -p build

for DIST in $DISTS; do
   [ -f debootstrap/$DIST ] || (echo "buildall: Unknown distribution: $DIST" && exit 1)
   echo "============================================"
   echo "Building $BASENAME:$DIST"
   echo "============================================"
   ./mkimage build/$DIST.tar $DIST
   IMPORTED=$(docker import --change "CMD /bin/bash" build/$DIST.tar)
   echo "============================================"
   echo "Running tests for $BASENAME:$DIST"
   echo "============================================"
   ./test $IMPORTED
   docker tag $IMPORTED $BASENAME:$DIST
   docker tag $IMPORTED $GCR_BASENAME:$DIST
done
docker tag $BASENAME:$LATEST $BASENAME:latest
docker tag $GCR_BASENAME:$LATEST $GCR_BASENAME:latest
