#!/bin/bash

set -e
set -u
set -o pipefail

IMAGE1=$1
IMAGE2=$2

inspect() {
    docker inspect $1 | jq ".[0]|del(.Id,.RepoTags,.RepoDigests,.Created)"
}

lslr() {
    docker run --rm $1 ls -lR /
}

if ! diff -u <(inspect $IMAGE1) <(inspect $IMAGE2); then
    diff -u <(lslr $IMAGE1) <(lslr $IMAGE2)
    exit 1
fi
