#!/bin/bash

set -e
set -u
set -o pipefail

DISTS="jessie
unstable
latest
"

BASENAME=bitnami/minideb
GCR_BASENAME=gcr.io/bitnami-containers/minideb
QUAY_BASENAME=quay.io/bitnami/minideb

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
fi

if [ -n "${QUAY_PASSWORD:-}" ]; then
    docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD
fi

if [ -n "${GCR_KEY:-}" ]; then
    gcloud auth activate-service-account $GCR_EMAIL --key-file <(echo "$GCR_KEY")
fi

for DIST in $DISTS; do
    docker push $BASENAME:$DIST
    docker push $QUAY_BASENAME:$DIST
    gcloud docker push $GCR_BASENAME:$DIST
done
