#!/bin/bash

set -e
set -u
set -o pipefail

DISTS="bullseye
bookworm
"
LATEST=bookworm
BASENAME=bitnami/minideb

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
fi

push() {
    local dist="$1"
    local image="${BASENAME}:${dist}"
    docker push "${image}"
    
    if [ -n "${COSIGN_PRIVATE_KEY:-}" ] && [ -n "${COSIGN_PASSWORD:-}" ]; then
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${image}"
    fi
}

for DIST in $DISTS; do
    push "$DIST"
done

docker tag "${BASENAME}:${LATEST}" "${BASENAME}:latest"

push latest

# Create and merge a PR to update minideb-extras
CIRCLE_CI_FUNCTIONS_URL=${CIRCLE_CI_FUNCTIONS_URL:-https://raw.githubusercontent.com/bitnami/test-infra/master/circle/functions}
# sc can't follow source as it is a remote file
# shellcheck disable=SC1090
source <(curl -sSL "$CIRCLE_CI_FUNCTIONS_URL")
for DIST in $DISTS; do
    # Use '.RepoDigests 0' for getting Dockerhub repo digest as it was the first pushed
    DIST_REPO_DIGEST=$(docker image inspect --format '{{index .RepoDigests 0}}' "${BASENAME}:${DIST}")
    update_minideb_derived "https://github.com/bitnami/minideb-runtimes" "$DIST" "$DIST_REPO_DIGEST"
done
