#!/bin/bash

set -e
set -u
set -o pipefail

DIST=${1:?Specify the distrubution name}
PLATFORM=${2:-amd64}

BASENAME=bitnami/minideb
DOCKER_REGISTRY=${DOCKER_REGISTRY:-"docker.io"}

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "${DOCKER_REGISTRY}"
fi

ENABLE_DOCKER_CONTENT_TRUST=0
if [ -n "${DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE:-}" ] && [ -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY:-}" ]; then
    tmpdir=$(mktemp -d)
    (cd "${tmpdir}" && bash -c 'echo -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY}" | base64 -d > key')
    chmod 400 "${tmpdir}/key"
    docker trust key load "${tmpdir}/key"
    rm -rf "${tmpdir}"
    export ENABLE_DOCKER_CONTENT_TRUST=1
fi

push() {
    local dist="$1"
    docker tag "${BASENAME}:${dist}" "${DOCKER_REGISTRY}/${BASENAME}:${dist}"
    DOCKER_CONTENT_TRUST=${ENABLE_DOCKER_CONTENT_TRUST} docker push "${DOCKER_REGISTRY}/${BASENAME}:${dist}"
}

push "$DIST-${PLATFORM}"
