# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Move closed issues'
on:
  issues:
    types:
      - closed
  pull_request_target:
    types:
      - closed
permissions:
  issues: write
  pull-requests: write
# Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event.issue != null && github.event.issue.number || github.event.number }}
jobs:
  call-move-closed-workflow:
    uses: bitnami/support/.github/workflows/item-closed.yml@main
    secrets: inherit