# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Move closed issues'
on:
  issues:
    types:
      - closed
  pull_request_target:
    types:
      - closed
permissions:
  issues: write
  pull-requests: write
jobs:
  call-move-closed-workflow:
    uses: bitnami/support/.github/workflows/item-closed.yml@main
    secrets: inherit