# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] PR review comment card movements'
on:
  pull_request_review_comment:
    types:
      - created
permissions: {}
# Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event.pull_request.number }}
jobs:
  just-notice:
    # This is a dummy workflow that triggers a workflow_run
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice:: Comment on PR #${{ github.event.pull_request.number }}"
          echo "${{ github.event.pull_request.number }}" > pull_request_number
      - name: Upload the PR number
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: pull_request_number
          path: ./pull_request_number