# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Review based card movements'
on:
  pull_request_target:
    types:
      - labeled
  issues:
    types:
      - labeled
permissions:
  contents: read
  pull-requests: write
  issues: write
# Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event.issue != null && github.event.issue.number || github.event.number }}
jobs:
  call-reasign-workflow:
    uses: bitnami/support/.github/workflows/item-labeled.yml@main
    secrets: inherit