# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

# This workflow is built to manage the triage support by using GH issues.
name: '[Support] Organize triage'
on:
  issues:
    types:
      - reopened
      - opened
  pull_request_target:
    types:
      - reopened
      - opened
permissions:
  contents: read
  pull-requests: write
  issues: write
# Avoid concurrency over the same issue
concurrency:
  group: card-movement-${{ github.event.issue != null && github.event.issue.number || github.event.number }}
jobs:
  call-triage-workflow:
    uses: bitnami/support/.github/workflows/item-opened.yml@main
    secrets: inherit